export const MEAL_OPTIONS = {
  breakfast: [
    "Boiled lobhia sauté with veggies [30% Lobhia & 70% veggies: Onion, tomato, capsicum, lemon]",
    "Boiled kala chana sauté with veggies [30% kalachana & 70% veggies: Onion, tomato, capsicum, lemon]",
    "Boiled soybean sauté with veggies [30% soybean & 70% veggies: Onion, tomato, capsicum, lemon]",
    "Boiled chhole sauté with veggies [30% chhole & 70% veggies: Onion, tomato, capsicum, lemon]",
    "Steam sprouts sauté with veggies [30% moong sprouts & 70% veggies: Onion, tomato, capsicum, lemon]",
    "Onion stuffed roti [flour, onion, dhaniya, green chilli]",
    "Lauki stuffed roti [flour, lauki, green chilli, coriander leaves]",
    "Palak stuffed roti [flour, palak, green chilli]",
    "Gobhi stuffed roti [flour, gobhi, onion, dhaniya, green chilli]",
    "Methi stuffed roti [flour, methi, green chilli]",
    "Kaddu stuffed roti [flour, kaddu, onion, dhaniya, green chilli]",
    "Aalu Paratha [flour, aalu, onion, dhaniya, green chilli]",
    "Paneer stuffed roti [flour, 30gm homemade paneer, onion, dhaniya, green chilli]",
    "Vegetable poha [30% rice flakes, 70% veggies: onion, tomato, capsicum, beans, carrot, lemon]",
    "Sprouts Poha [30% rice flakes, 70% veggies: onion, tomato, capsicum, beans, 30gm steam moong, lemon]",
    "Veg Wheat daliya [30% daliya, 70% veggies: onion, tomato, capsicum, beans]",
    "Vegetable sabudana [30% sabudana & peas, 70% veggies: onion, tomato, capsicum, beans]",
    "Besan cheela veg [add tomato, onion, ginger, capsicum, beans in cheela]",
    "Veg sandwich [green chutney on 2 atta bread slices, tomato, onion, cucumber, bell pepper, lemon]",
    "2 Oats idli sauté with vegetables [tomato, onion, capsicum, beans, carrot]",
    "2 Rava idli sauté with vegetables [tomato, onion, capsicum, beans, carrot]",
    "2 Idli (dal rice FERMENTED) sauté with vegetables [tomato, onion, capsicum, beans, carrot]",
    "Ragi cheela veg [add tomato, onion, ginger, capsicum, beans in cheela]",
    "Moong dal cheela veg [add tomato, onion, ginger, capsicum, beans in cheela]",
    "Paneer veg sandwich [tomato, onion, 30gm homemade paneer, capsicum, lemon, 2 atta bread slices]",
    "Soy veg sandwich [tomato, onion, 20gm soya, capsicum, lemon, 2 atta bread slices]",
    "30gm muesli without nuts with 200ml low fat milk",
    "30gm plain cornflakes with 200ml low fat milk",
    "Egg omelette [3 egg whites, beans, tomato, onion, bell peppers, ajwain, coriander leaves]",
    "Vegetable oats [70% veggies: tomato, capsicum, grated amla, onion, 30% plain oats]",
    "Veg upma [30% suji, 70% veggies: onion, tomato, capsicum, beans, carrot, lemon]",
    "1 Veg uttapam [add veggies: onion, tomato, capsicum, beans, carrot]",
    "Suji cheela veg mix [30% suji, 70% veggies: onion, tomato, capsicum, beans, carrot]",
    "Boiled egg [3 boiled egg whites, tomato, onion, bell peppers, ajwain, coriander leaves]",
    "Toned milk",
    "Double toned milk",
    "Cow's milk",
    "Chhach",
    "Curd"
  ],
  
  midMorning: [
    "1 Seasonal fruit",
    "1 Apple",
    "1 Pear",
    "1 Orange",
    "Mausmbi",
    "150gm papaya",
    "1-2 Kiwi",
    "8 Singhare",
    "1 Custard apple",
    "1 Banana",
    "1 Mango",
    "1-2 Chikoo",
    "Watermelon",
    "Muskmelon",
    "Guava",
    "200ml chhach",
    "1 Glass Chia seeds water",
    "1 Glass water with 1 teaspoon flax seeds",
    "1 Glass fresh coconut water"
  ],
  
  lunch: {
    roti: ["Jawar roti", "Jowar roti", "Bajra roti", "Ragi roti", "Wheat bran mix [30% wheat bran, 70% wheat flour]", "Black wheat roti", "Boiled white rice", "Steamed white rice", "Boiled brown rice", "Steamed brown rice"],
    subji: ["Beans veg", "Palak paneer [50gm homemade paneer]", "Aalu gobhi veg", "Gobhi tomato veg", "Cabbage peas veg", "Broccoli veg", "Aalu tomato gravy veg", "Lauki chana dal", "Lauki tomato veg", "Capsicum Aalu", "Capsicum tomato onion", "Mushroom capsicum", "Tinda veg", "Tori veg", "Kundru veg", "Kaddu veg", "Bhindi veg", "Spring onion veg", "Palak curry", "Mooli bhurji", "Green banana veg", "Arvi gravy veg", "Mutter mushroom"],
    dal: ["Arher dal", "Moong dal", "Chana dal", "Masoor dal", "Urad chana dal", "Kadhi without pakori", "Palak kadhi without pakori", "Spring onion kadhi without pakori", "Rajhma", "Chhole", "Kala chana gravy", "Lobhia gravy", "Gatte ki subji without fried", "Nutreela veg", "2 Rava idli with 1 bowl sambhar", "2 Dal rice fermented Idli with 1 bowl sambhar", "2 Oats idli with 1 bowl sambhar", "Sambhar", "Pav bhaji [wheat pav]", "2 Plain dosa with sambhar"],
    salad: "Cucumber, tomato, onion, carrot, lemon",
    yogurt: ["Chhach", "Curd"]
  },
  
  eveningSnacks: [
    "Murmura bhel [handful murmura, tomato, kheera, onion, green chutney, lemon]",
    "Corn bhel [handful cornflakes, tomato, kheera, onion, green chutney, lemon]",
    "Mix bhel [half handful murmura, half handful bhuna chana, 2 spoons cornflakes, tomato, kheera, onion, green chutney, lemon]",
    "Veg sandwich [green chutney on 2 atta bread slices, tomato, onion, cucumber, bell pepper, lemon]",
    "Handful bhuna chana",
    "Handful dry roasted makhane",
    "Handful dry murmura",
    "Handful plain corn flakes",
    "Handful puffed bajra",
    "Handful puffed jowar",
    "Tea (less sugar, less milk)",
    "Green tea",
    "1 Cup cold milk"
  ],
  
  dinner: {
    options: ["Vegetable oats [70% veggies: tomato, capsicum, grated amla, onion, 30% plain oats]", "Veg upma [30% suji, 70% veggies: onion, tomato, capsicum, beans, carrot, lemon]", "Veg Black Wheat daliya [30% daliya, 70% veggies: onion, tomato, capsicum, beans]", "Veg barley daliya [30% barley, 70% veggies: onion, tomato, capsicum, beans]", "Veg Millet daliya [30% millet, 70% veggies: onion, tomato, capsicum, beans]", "Onion stuffed roti [flour, onion, dhaniya, green chilli]", "Lauki stuffed roti [flour, lauki, green chilli, coriander leaves]", "Palak stuffed roti [flour, palak, green chilli]", "Gobhi stuffed roti [flour, gobhi, onion, dhaniya, green chilli]", "Methi stuffed roti [flour, methi, green chilli]", "Kaddu stuffed roti [flour, kaddu, onion, dhaniya, green chilli]", "Vegetable poha [30% rice flakes, 70% veggies: onion, tomato, capsicum, beans, carrot, lemon]", "Ragi cheela veg [add tomato, onion, ginger, capsicum, beans in cheela]", "Moong dal cheela veg [add tomato, onion, ginger, capsicum, beans in cheela]", "2 Oats idli sauté with vegetables [tomato, onion, capsicum, beans, carrot]", "2 Rava idli sauté with vegetables [tomato, onion, capsicum, beans, carrot]", "2 Idli (dal rice FERMENTED) sauté with vegetables [tomato, onion, capsicum, beans, carrot]", "Veg sandwich [green chutney on 2 atta bread slices, tomato, onion, cucumber, bell pepper, lemon]"],
    roti: ["Jawar roti", "Jowar roti", "Bajra roti", "Ragi roti", "Wheat bran mix [30% wheat bran, 70% wheat flour]", "Black wheat roti", "Boiled white rice", "Steamed white rice", "Boiled brown rice", "Steamed brown rice"],
    subji: ["Beans veg", "Palak paneer [50gm homemade paneer]", "Aalu gobhi veg", "Gobhi tomato veg", "Cabbage peas veg", "Broccoli veg", "Aalu tomato gravy veg", "Lauki chana dal", "Lauki tomato veg", "Capsicum Aalu", "Capsicum tomato onion", "Mushroom capsicum", "Tinda veg", "Tori veg", "Kundru veg", "Kaddu veg", "Bhindi veg", "Spring onion veg", "Palak curry", "Mooli bhurji", "Green banana veg", "Arvi gravy veg", "Mutter mushroom"],
    dal: ["Arher dal", "Moong dal", "Chana dal", "Masoor dal", "Rajhma", "Chhole", "Kala chana gravy", "Lobhia gravy", "Nutreela veg", "2 Rava idli with 1 bowl sambhar", "2 Dal rice fermented Idli with 1 bowl sambhar", "2 Oats idli with 1 bowl sambhar", "Sambhar", "Pav bhaji [wheat pav]", "2 Plain dosa with sambhar"]
  }
};